[tool.poetry]
name = "duckdb-ast"
version = "0.1.0"
description = ""
authors = ["Elliana May <me@mause.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "duckdb_ast"}]

[tool.poetry.dependencies]
python = "^3.8"
duckdb = {version = "^0.7.2.dev899", allow-prereleases = true}
pydantic = "^1.10.6"

[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
rich = "^13.3.2"
pytest = "^7.2.2"
snapshottest = "^0.6.0"
pre-commit = "^3.2.0"
sphinx = "^6.1.3"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
