[tool.poetry]
name = "duckdb-ast"
version = "0.1.0"
description = ""
authors = ["Elliana May <me@mause.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "duckdb_ast"}]

[tool.poetry.dependencies]
python = "^3.8"
duckdb = "^0.8.1"
pydantic = "^2.0.3"

[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
rich = "^13.4.2"
pytest = "^7.3.1"
snapshottest = {git = "https://github.com/syrusakbary/snapshottest"}
pre-commit = "^3.3.3"
sphinx = "^7.0.1"
mypy = "^1.4.1"
sphinx-autoapi = "^2.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
